### ISSUE TITLE
i3status colors

### ISSUE THREAD

**Issue by anselal** [andreatta/config#1]
Hi there,

I saw your post on reddit and I really liked your i3status bar, especially your colored workspace icons.

I have enabled colors in my i3status.conf file but the icons still appear grey.

Do you have any suggestions how to resolve this issue ? 
I am using i3-gaps on openSUSE Leap 15.0 and I use Hack Nerd Font Mono as a font.

**Comment by andreatta** [comment]
Hi,

It's been some time since I was on Reddit. Could you share the link you referring to?

**Comment by anselal** [comment]
thank you for the quick reply.

I can't find the post in my browser's history this is why I opened an issue here.
The screenshot you posted is this one https://github.com/andreatta/config/blob/master/i3/i3-screen2.png

If that helps, I will look for the post again and let you know ...

**Comment by andreatta** [comment]
Yeah, I thought it might be this one.
Sorry, but this is not i3-status. It was my first setup with XFCE-bar from when I was switching from xubuntu to i3.
I am closing this issue, but feel free to ask further questions.

**Comment by anselal** [comment]
This explains a lot. I was trying for hours to make this work.
Thank you for the clarification !!!
